### PR TITLE
Update RandomHearth.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**
It's all samples that I've done a good job of CN localising. Sometime you are doing full language localisation.

### CODE REVIEW

**Comment by JamienAU** [comment]
Thank you for adding this!
I will try creating a localisation table and adding the translations.

**Comment by nanjuekaien1** [comment]
Thank you
I used your RandomHearth plugin in 2022. I've wanted to contact you to apply for localization.
Post closed by me, don't mislead others.

**Comment by nanjuekaien1** [comment]
Once the localisation was done, I called out BlueNightSky to do the translation of TW.

**Comment by JamienAU** [comment]
Can you please try this version? I have added your translations and attempted to replace all text.

https://github.com/JamienAU/RandomHearth/tree/localisation

**Comment by nanjuekaien1** [comment]
perfect

## Notes-zhCN: 使用随机炉石玩具

**Comment by nanjuekaien1** [comment]
I've left a message for the TW localisation guy to submit it when he has time.

**Comment by nanjuekaien1** [comment]
I don't know if you noticed 210455, --Draenic Hologem has conditions of use.

Only draenei and lightforged draenei can use the draenic hologem.

**Comment by JamienAU** [comment]
Thanks :) I had some logic in there to restrict it to Draenai only, but I had it coded incorrectly.
I've updated it and tested, looks to be working now

**Pull request closed without merging**
